document.writeln('<table width=\"98%\" border=\"0\" align=\"center\">')
document.writeln('<form id=\"SearchForm\" name=\"SearchForm\" method=\"get\" action=\"/plus/Search.asp\">')
document.writeln('  <tr>')
document.writeln('    <td align=\"center\"><select name=\"SearchType\">')
document.writeln('          <option value=\"1\">商品名称</option>')
document.writeln('          <option value=\"2\">生 产 商</option>')
document.writeln('          <option value=\"3\">商品介绍</option>')
document.writeln('          <option value=\"5\">商品Tags</option>')
document.writeln('      </select>')
document.writeln('        <select name=\"ClassID\" style=\"width:150\">')
document.writeln('          <option value=\"0\" selected=\"selected\">所有栏目</option>')
document.writeln('<option value=\'20103299686040\'>dd </option>        </select>')
document.writeln('        <input name=\"KeyWord\" type=\"text\" class=\"textbox\"  value=\"关键字\" onfocus=\"this.select();\"/>')
document.writeln('        <input name=\"ChannelID\" value=\"5\" type=\"hidden\" />')
document.writeln('        <input type=\"submit\" class=\"inputButton\" name=\"Submit\" value=\"搜 索\" /></td>')
document.writeln('  </tr>')
document.writeln('</form>')
document.writeln('</table>')
